version: '3.9'

services:
  api_1:
    image: vendas_img
    container_name: api_1
    env_file: .env
    environment:
      - MONGO_URI=mongodb://database:27017/vendas
      - REDIS_URI=redis://cache_service:6379
    ports:
      - 3000
    networks:
      - vendas_networks
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 80M
    depends_on:
      - database
  
  api_2:
    image: vendas_img
    container_name: api_2
    env_file: .env
    environment:
      - MONGO_URI=mongodb://database:27017/vendas
      - REDIS_URI=redis://cache_service:6379
    ports:
      - 3000
    networks:
      - vendas_networks
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 80M
    depends_on:
      - database

  api_3:
    image: vendas_img
    container_name: api_3
    env_file: .env
    environment:
      - MONGO_URI=mongodb://database:27017/vendas
      - REDIS_URI=redis://cache_service:6379
    ports:
      - 3000
    networks:
      - vendas_networks
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 80M
    depends_on:
      - database


  database:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    networks:
      - vendas_networks
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    volumes:
      - './src/infra/database/mongodb/scripts:/data/scripts:rw'

  cache_service:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    networks:
      - vendas_networks

  balanceador:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:rw
    ports:
      - 8080:3000
    networks:
      - vendas_networks
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
    depends_on:
      - api_1
      - api_2
      - api_3
  
  queue_service:
    image: 'rabbitmq:management'
    container_name: 'queue_service'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=adm
      - RABBITMQ_DEFAULT_PASS=adm
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vendas_networks

networks:
  vendas_networks: {}
